In [1]:
# Customer Orders Inspection
Exploratory Data Analysis of an E-commerce Orders Dataset

**Name:** Your Name
**Date:** YYYY-MM-DD

SyntaxError: invalid syntax (1385287696.py, line 2)

# Customer Orders Inspection
Exploratory Data Analysis of an E-commerce Orders Dataset

**Name:** Your Name  
**Date:** YYYY-MM-DD

In [2]:
import pandas as pd

In [4]:
url = "https://drive.google.com/uc?id=1Mlu9r3afSGz5_02Y3wDJoQLpXszQXaIU"

df = pd.read_csv(url, index_col="order_id")

df.head()

          customer_name   product  quantity  unit_price  order_date     status
order_id
1001      Alice Johnson    Laptop       1.0     85000.0  2024-01-15  delivered
1002          Bob Smith     Mouse       3.0       499.0  2024-01-16    pending
1003        Carol White   Monitor       2.0     15000.0         NaN  delivered
1004         Dave Brown  Keyboard       NaN      1200.0  2024-01-18  cancelled
1005          Eva Green    Laptop       1.0     85000.0  2024-01-19  delivered

In [6]:
df.tail()

         customer_name   product  quantity  unit_price  order_date     status
order_id
1016       Paul Harris     Mouse       6.0       499.0  2024-01-30    pending
1017      Quinn Martin   Monitor       NaN     14500.0  2024-01-31  delivered
1018       Rachel King    Laptop       1.0     85000.0         NaN  delivered
1019        Sam Wright  Keyboard       3.0      1200.0  2024-02-01  cancelled
1020        Tina Baker   USB Hub       2.0       799.0  2024-02-02    pending

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 1001 to 1020
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_name  20 non-null     object
 1   product        20 non-null     object
 2   quantity       16 non-null     float64
 3   unit_price     20 non-null     float64
 4   order_date     16 non-null     object
 5   status         20 non-null     object
dtypes: float64(2), object(4)
memory usage: 1.1+ KB

In [9]:
df.shape

(20, 6)

In [10]:
df.isnull().sum()

customer_name    0
product          0
quantity         4
unit_price       0
order_date       4
status           0
dtype: int64

## Structural Inspection Results

**1. Dataset Shape**

The dataset contains **X rows and Y columns**.

**2. Missing Values**

The following columns contain missing values:

- column_name → X missing values
- column_name → X missing values

(From df.isnull().sum())

**3. Column Requiring Data Type Conversion**

The **order_date** column is stored as an **object (string)**.

Before performing date-based analysis it should be converted using:

```python
df["order_date"] = pd.to_datetime(df["order_date"])


---

# 🔹 Task 3 — Statistical Summary

**Code Cell**

```python
df.describe()

## Statistical Summary

**1. Median unit_price**

The median value of **unit_price** is **X**.

(This is the **50% value** from df.describe().)

**2. Distribution of unit_price**

The column appears **right-skewed** if:

- mean > median
- max is far larger than the 75th percentile

or **left-skewed** if:

- mean < median

From the summary statistics we observe:

- Mean = X
- Median = X
- Max = X

This indicates the distribution is **(right/left/approximately symmetric)**.

In [11]:
df["order_date"] = pd.to_datetime(df["order_date"])
df.head()

          customer_name   product  quantity  unit_price order_date     status
order_id
1001      Alice Johnson    Laptop       1.0     85000.0 2024-01-15  delivered
1002          Bob Smith     Mouse       3.0       499.0 2024-01-16    pending
1003        Carol White   Monitor       2.0     15000.0        NaT  delivered
1004         Dave Brown  Keyboard       NaN      1200.0 2024-01-18  cancelled
1005          Eva Green    Laptop       1.0     85000.0 2024-01-19  delivered