In [2]:
import pandas as pd
import numpy as np

Task 1 — Load and Inspect the Data

In [3]:
data = {
    'transaction_id': range(1, 21),
    'date': pd.date_range('2024-10-01', periods=20, freq='D'),
    'region': ['North', 'South', 'East', 'West', None, 'North', 'South', None, 'East', 'West',
               'North', 'South', 'East', 'West', 'North', None, 'East', 'West', 'North', 'South'],
    'product_category': ['Electronics', 'Clothing', None, 'Books', 'Electronics', 'Home',
                         'Clothing', 'Books', 'Electronics', None, 'Home', 'Clothing',
                         'Books', 'Electronics', 'Home', 'Clothing', 'Books', 'Electronics',
                         'Home', 'Clothing'],
    'sales_amount': [1200, 450, 890, None, 1500, 670, None, 340, 2100, 780,
                     560, None, 420, 1800, 920, 510, 380, None, 1100, 640],
    'quantity': [2, 5, 3, 1, None, 4, 2, 3, 1, 5,
                 3, 2, None, 1, 4, 3, 2, 1, None, 4],
    'customer_age': [25, 34, None, 45, 29, None, 38, 52, 27, 41,
                     33, None, 48, 26, 35, 42, None, 31, 39, 44],
    'payment_method': ['Credit Card', 'UPI', 'Cash', 'Debit Card', 'Credit Card',
                       'UPI', 'Cash', None, 'Credit Card', 'UPI', 'Debit Card',
                       'Cash', 'Credit Card', None, 'UPI', 'Cash', 'Debit Card',
                       'Credit Card', 'UPI', None]
}

df = pd.DataFrame(data)
df

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,None,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,NaN,1.0,45.0,Debit Card
4,5,2024-10-05,None,Electronics,1500.0,NaN,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,NaN,2.0,38.0,Cash
7,8,2024-10-08,None,Books,340.0,3.0,52.0,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,None,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,NaN,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,NaN,48.0,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,None
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,None,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,NaN,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,NaN,39.0,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,None

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    20 non-null     int64
 1   date              20 non-null     datetime64[ns]
 2   region            17 non-null     object
 3   product_category  18 non-null     object
 4   sales_amount      16 non-null     float64
 5   quantity          17 non-null     float64
 6   customer_age      16 non-null     float64
 7   payment_method    17 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 1.4+ KB

In [5]:
df.isna().sum()

transaction_id      0
date                0
region              3
product_category    2
sales_amount        4
quantity            3
customer_age        4
payment_method      3
dtype: int64

In [6]:
df.isna().sum().sum()

np.int64(19)

Task 2: Handle Missing Values
Clean the dataset using appropriate strategies:

Region & Product_category: Fill with mode (most frequent value)
Sales_amount: Fill with median
Quantity: Fill using forward fill (ffill)
Customer_age: Fill with mean (rounded to integer)
Payment_method: Drop rows where payment_method is missing
Verify no missing values remain using df.isna().sum()

In [11]:
#Fill region with mode
df['region'].fillna(df['region'].mode()[0])

0     North
1     South
2      East
3      West
4     North
5     North
6     South
7     North
8      East
9      West
10    North
11    South
12     East
13     West
14    North
15    North
16     East
17     West
18    North
19    South
Name: region, dtype: object

In [12]:
#Fill product_category with mode
df['product_category'].fillna(df['product_category'].mode()[0])

0     Electronics
1        Clothing
2        Clothing
3           Books
4     Electronics
5            Home
6        Clothing
7           Books
8     Electronics
9        Clothing
10           Home
11       Clothing
12          Books
13    Electronics
14           Home
15       Clothing
16          Books
17    Electronics
18           Home
19       Clothing
Name: product_category, dtype: object

In [14]:
#Fill sales_amount with median
df['sales_amount'].fillna(df['sales_amount'].median())

0     1200.0
1      450.0
2      890.0
3      725.0
4     1500.0
5      670.0
6      725.0
7      340.0
8     2100.0
9      780.0
10     560.0
11     725.0
12     420.0
13    1800.0
14     920.0
15     510.0
16     380.0
17     725.0
18    1100.0
19     640.0
Name: sales_amount, dtype: float64

In [21]:
#Fill quantity using forward fill
#df['quantity'].fillna(method='ffill')
df['quantity'].ffill()

0     2.0
1     5.0
2     3.0
3     1.0
4     1.0
5     4.0
6     2.0
7     3.0
8     1.0
9     5.0
10    3.0
11    2.0
12    2.0
13    1.0
14    4.0
15    3.0
16    2.0
17    1.0
18    1.0
19    4.0
Name: quantity, dtype: float64

In [23]:
#Fill customer_age with mean
#df['customer_age'].fillna(round(df['customer_age'].mean()), inplace=True)
df['customer_age'].fillna(round(df['customer_age'].mean()))

0     25.0
1     34.0
2     37.0
3     45.0
4     29.0
5     37.0
6     38.0
7     52.0
8     27.0
9     41.0
10    33.0
11    37.0
12    48.0
13    26.0
14    35.0
15    42.0
16    37.0
17    31.0
18    39.0
19    44.0
Name: customer_age, dtype: float64

In [24]:
#Drop rows where payment_method is missing
df.dropna(subset=['payment_method'])

,transaction_id,date,region,product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,Clothing,890.0,3.0,37.0,Cash
3,4,2024-10-04,West,Books,725.0,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,1.0,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,37.0,UPI
6,7,2024-10-07,South,Clothing,725.0,2.0,38.0,Cash
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,Clothing,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,725.0,2.0,37.0,Cash
12,13,2024-10-13,East,Books,420.0,2.0,48.0,Credit Card
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,37.0,Debit Card
17,18,2024-10-18,West,Electronics,725.0,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,1.0,39.0,UPI

In [25]:
#Verify No Missing Values
df.isna().sum()

transaction_id      0
date                0
region              0
product_category    0
sales_amount        0
quantity            0
customer_age        0
payment_method      3
dtype: int64

Task 3 — GroupBy Analysis

In [26]:
#Total Sales by Region
df.groupby('region')['sales_amount'].sum()

region
East     3790.0
North    6800.0
South    2540.0
West     4030.0
Name: sales_amount, dtype: float64

In [27]:
#Average Sales by Product Category
df.groupby('product_category')['sales_amount'].mean()

product_category
Books           466.250000
Clothing        674.285714
Electronics    1465.000000
Home            812.500000
Name: sales_amount, dtype: float64

In [28]:
#Group by Region and Product Category
region_product_sales = df.groupby(
    ['region', 'product_category']
)[['sales_amount', 'quantity']].sum().reset_index()

region_product_sales

   region product_category  sales_amount  quantity
0    East            Books         800.0       4.0
1    East         Clothing         890.0       3.0
2    East      Electronics        2100.0       1.0
3   North            Books         340.0       3.0
4   North         Clothing         510.0       3.0
5   North      Electronics        2700.0       3.0
6   North             Home        3250.0      12.0
7   South         Clothing        2540.0      13.0
8    West            Books         725.0       1.0
9    West         Clothing         780.0       5.0
10   West      Electronics        2525.0       2.0

In [29]:
#Top 3 Region-Product Combinations by Sales
region_product_sales.sort_values(
    by='sales_amount', ascending=False
).head(3)

  region product_category  sales_amount  quantity
6  North             Home        3250.0      12.0
5  North      Electronics        2700.0       3.0
7  South         Clothing        2540.0      13.0

Task 4 — Custom Aggregation

In [31]:
#Create Custom Function
def sales_range(x):
    return x.max() - x.min()

In [32]:
#Sales Range by Region
df.groupby('region')['sales_amount'].apply(sales_range)

region
East     1720.0
North    1160.0
South     275.0
West     1075.0
Name: sales_amount, dtype: float64

In [33]:
#Multiple Aggregations Using .agg()
df.groupby('region').agg({
    'sales_amount': ['sum', 'mean', 'max'],
    'quantity': ['sum', 'min']
})

       sales_amount                 quantity
                sum    mean     max      sum  min
region
East         3790.0   947.5  2100.0      8.0  1.0
North        6800.0   850.0  1500.0     21.0  1.0
South        2540.0   635.0   725.0     13.0  2.0
West         4030.0  1007.5  1800.0      8.0  1.0